### ISSUE TITLE
New passwords/logins after reboot

### ISSUE THREAD

**Issue by asgh** [PolyPasswordHasher/PolyPasswordHasher#6]
Until the server has calculated the "line" is it possible to register new accounts? Or does it need a bunch of correct logins first so it can do the necessary math, and only then register accounts?

**Comment by SantiagoTorres** [comment]
Hi @asgh, thanks for contacting us!

If the server doesn't have information about the secret it can still create new accounts. The difference is that these accounts are created as regular salted hashes until the secret is available. Once the secret is available, the accounts salted hashes are updated into their encrypted form.

Let me know if this answers your question.

**Comment by asgh** [comment]
It does answer the question. (So you should add this info to the readme and then close this issue.)

**Comment by SantiagoTorres** [comment]
You are right. I'll add this soon and close this issue once it is added.

Thanks for your feedback!
